// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.Data;

#nullable disable

namespace NZWalks.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20260620203325_RegionsAndWalksData")]
    partial class RegionsAndWalksData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b1ac5bb-9241-47c8-9217-ac21ae9f1c88"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("8e482dcb-811b-4abc-873d-8e2bcb092381"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("270c8c35-d791-4346-a0af-cf944cecc6e7"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0529e642-73fa-4937-b127-a8841ab27ec5"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Auckland_Region_location_in_New_Zealand.svg/250px-Auckland_Region_location_in_New_Zealand.svg.png"
                        },
                        new
                        {
                            Id = new Guid("bba41656-6ba9-4e78-bac6-446ae3597cfc"),
                            Code = "WTC",
                            Name = "West Coast",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/West_Coast_Region_location_in_New_Zealand.svg/250px-West_Coast_Region_location_in_New_Zealand.svg.png"
                        },
                        new
                        {
                            Id = new Guid("c2cc249f-ec19-48ba-8898-e71cba88ea1f"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Wellington_Region_location_in_New_Zealand.svg/250px-Wellington_Region_location_in_New_Zealand.svg.png"
                        },
                        new
                        {
                            Id = new Guid("8531ecb9-509a-4130-b384-56b9c97b2d56"),
                            Code = "CAN",
                            Name = "Canterbury",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Canterbury_Region_location_in_New_Zealand.svg/250px-Canterbury_Region_location_in_New_Zealand.svg.png"
                        },
                        new
                        {
                            Id = new Guid("2bd150db-ebf5-4420-b4da-39d3ad60f1b1"),
                            Code = "OTA",
                            Name = "Otago",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Otago_Region_location_in_New_Zealand.svg/250px-Otago_Region_location_in_New_Zealand.svg.png"
                        },
                        new
                        {
                            Id = new Guid("3b1e32dc-a9ff-4d11-b06c-82e057398b50"),
                            Code = "WKO",
                            Name = "Waikato",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Waikato_Region_location_in_New_Zealand.svg/250px-Waikato_Region_location_in_New_Zealand.svg.png"
                        },
                        new
                        {
                            Id = new Guid("6787889d-7db0-47b0-8c20-7f5fb9c9ff45"),
                            Code = "BOP",
                            Name = "Bay Of Plenty",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Bay_of_Plenty_Region_location_in_New_Zealand.svg/250px-Bay_of_Plenty_Region_location_in_New_Zealand.svg.png"
                        });
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKM")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
